[mcp_servers.aws-iac-mcp-server]
command = "uv"
args = ["run", "awslabs.aws-iac-mcp-server"]

[mcp_servers.aws-iac-mcp-server.env]
AWS_PROFILE = "master"
FASTMCP_LOG_LEVEL = "ERROR"

[mcp_servers.nixos]
command = "uv"
args = ["run", "mcp-nixos"]

[mcp_servers.textlint]
command = "vp"
args = ["exec", "textlint", "--mcp"]
