theme = "congo"
baseURL = "https://holidayworking.org"
enableRobotsTXT = true

locale = "ja"
title = "holidayworking.org"
hasCJKLanguage = true

[params]
dateFormat = "2 January 2006"
mainSections = ["blog"]
enableCodeCopy = true
enableImageWebp = false
photoBaseURL = "https://photo.holidayworking.org"

[params.author]
name = "Hidekazu Tanaka"
image = "img/author.jpg"
links = [{ github = "https://github.com/holidayworking" }]

[params.homepage]
layout = "profile"

[params.article]
showAuthor = false
showReadingTime = false
showTaxonomies = true

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "blog"
pageRef = "blog"
weight = 10

[social]
twitter = "holidayworking"
