theme = "congo"
baseURL = "https://holidayworking.org"
enableRobotsTXT = true

locale = "ja"
title = "holidayworking.org"
hasCJKLanguage = true

[params]
dateFormat = "2006年January2日"
mainSections = ["blog"]
enableCodeCopy = true
enableImageWebp = false
photoBaseURL = "https://photo.holidayworking.org"

[params.author]
name = "Hidekazu Tanaka"
image = "img/author.jpg"
links = [
  { bluesky = "https://bsky.app/profile/holidayworking.bsky.social" },
  { github = "https://github.com/holidayworking" },
]

[params.homepage]
layout = "profile"

[params.article]
showAuthor = false
showReadingTime = false
showTaxonomies = true
sharingLinks = ["facebook", "x-twitter", "bluesky", "mastodon"]

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "blog"
pageRef = "blog"
weight = 10


[[menu.main]]
name = "travel"
pageRef = "travel"
weight = 20

[social]
twitter = "holidayworking"
