name: Setup Docker
description: Set up Docker with the containerd image store and expose the GitHub Actions cache runtime.

runs:
  using: composite
  steps:
    - uses: docker/setup-docker-action@2bf61fb9464cc67f0cbdeabed6aa0380accd1c70 # v5.5.0
      with:
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": true
            }
          }
    - uses: crazy-max/ghaction-github-runtime@04d248b84655b509d8c44dc1d6f990c879747487 # v4.0.0
